INSERT INTO CGM_USERS (USER_NAME, PASSWORD, ROLE, LICENCE_ID)
VALUES ('admin', '$2a$10$AHOdkYdpITciueNcewVYqePnqlhKtviiyJBhud77gCWFTz4mK7K2S', 'ROLE_ADMIN', '');

INSERT INTO CGM_USERS (USER_NAME, PASSWORD, ROLE, LICENCE_ID)
VALUES ('user', '$2a$10$lcUxHABzvm0UO8IpwF/azOgXkwObpHNFGSHQag1ynYAKw1Sd7ms2W', 'ROLE_USER', '');

INSERT INTO CGM_CLIENT_DETAILS (CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, WEB_SERVER_REDIRECT_URI, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY, ADDITIONAL_INFORMATION, AUTOAPPROVE)
VALUES ('sampleClientId', '', null, 'read,write,authenticated,admin', 'implicit', 'http://localhost:8083/', '', 3600, 31536000, '{}', 'authenticated,read,admin,write')